export default defineEventHandler(() => {
  return {
    levelName: 'HSK 1',
    duration: 48,
    remainingDuration: 36,
    units: [
      {
        unitId: 4265,
        unitTitle: 'Bài giới thiệu',
      },
      {
        unitId: 4303,
        unitTitle: 'Khám phá 25 bộ cấu tạo nên chữ Hán cơ bản',
      },
      {
        unitId: 4305,
        unitTitle: 'Nâng cấp với 19 bộ cấu tạo nên chữ Hán mở rộng',
      },
      {
        unitId: 4307,
        unitTitle: 'Chinh phục Hán tự với 8 bộ cấu tạo nên chữ Hán nâng cao',
      },
      {
        unitId: 4414,
        unitTitle: 'Giới thiệu',
      },
      {
        unitId: 4707,
        unitTitle: 'Ngữ âm',
      },
      {
        unitId: 4415,
        unitTitle: 'Chủ đề 1 - Làm quen chữ Hán',
      },
      {
        unitId: 4418,
        unitTitle: 'Chủ đề 2 - 你忙吗？(Bạn bận không?)',
      },
      {
        unitId: 4416,
        unitTitle: 'Chủ đề 3 - 谢谢你！(Cảm ơn bạn!)',
      },
      {
        unitId: 4417,
        unitTitle: 'Chủ đề 4 - 你家有几口人？（Nhà bạn có mấy người?)',
      },
      {
        unitId: 4419,
        unitTitle: 'Chủ đề 5 - 她女儿今年二十岁。 (Năm nay con gái cô ấy 20 tuổi.)',
      },
      {
        unitId: 4435,
        unitTitle: 'Bài kiểm tra 1',
      },
      {
        unitId: 4420,
        unitTitle: 'Chủ đề 6 - 我会说汉语。(Tôi biết nói tiếng Trung.)',
      },
      {
        unitId: 4421,
        unitTitle: 'Chủ đề 7 - 今天星期几? (Hôm nay là thứ mấy?)',
      },
      {
        unitId: 4422,
        unitTitle: 'Chủ đề 8 - 我想喝奶茶。(Tôi muốn uống trà sữa.)',
      },
      {
        unitId: 4423,
        unitTitle: 'Chủ đề 9 - 你在哪儿工作? (Bạn làm việc ở đâu?)',
      },
      {
        unitId: 4424,
        unitTitle: 'Chủ đề 10 - 我能不能坐这儿？ (Tôi ngồi đây được không?)',
      },
      {
        unitId: 4436,
        unitTitle: 'Bài kiểm tra 2',
      },
      {
        unitId: 4425,
        unitTitle: 'Chủ đề 11 - 现在几点? (Bây giờ là mấy giờ?)',
      },
      {
        unitId: 4426,
        unitTitle: 'Chủ đề 12 - 明天天气怎么样? (Thời tiết ngày mai thế nào?)',
      },
      {
        unitId: 4427,
        unitTitle: 'Chủ đề 13 - 你在做什么呢？ (Bạn đang làm gì vậy?)',
      },
      {
        unitId: 4428,
        unitTitle: 'Chủ đề 14 - 我去商店买水果。(Tôi đi cửa hàng mua hoa quả.)',
      },
      {
        unitId: 4429,
        unitTitle: 'Chủ đề 15 - 我们是坐出租车来的。(Chúng tôi đến đây bằng xe taxi.)',
      },
      {
        unitId: 4437,
        unitTitle: 'Bài kiểm tra 3',
      },
      {
        unitId: 4430,
        unitTitle: 'Chủ đề 16 - 你喜欢不喜欢今天的电影？(Bạn có thích bộ phim ngày hôm nay không?)',
      },
      {
        unitId: 4431,
        unitTitle: 'Chủ đề 17 - 你想吃面包还是面条儿？ (Bạn muốn ăn bánh mỳ hay mỳ sợi?)',
      },
      {
        unitId: 4432,
        unitTitle: 'Chủ đề 18 - 我先介绍一下儿。 (Tôi giới thiệu trước một chút.)',
      },
      {
        unitId: 4433,
        unitTitle: 'Chủ đề 19 - 你跟我一起去买新的电视机吧！ (Hãy cùng tôi đi mua TV mới nhé!)',
      },
      {
        unitId: 4434,
        unitTitle: 'Chủ đề 20 - 我喜欢一边看书，一边喝茶。(Tôi thích vừa đọc sách vừa uống trà.)',
      },
      {
        unitId: 4438,
        unitTitle: 'Bài kiểm tra 4',
      },
      {
        unitId: 4439,
        unitTitle: 'Chủ đề 21 - 这块手表比我的手机还贵。(Chiếc đồng hồ này còn đắt hơn điện thoại của tôi.)',
      },
      {
        unitId: 4440,
        unitTitle: 'Chủ đề 22 - 学校里边有商店吗？(Bên trong trường học có cửa hàng không?)',
      },
      {
        unitId: 4441,
        unitTitle: 'Chủ đề 23 - 旁边是一家咖啡店。(Bên cạnh là một quán cafe.)',
      },
      {
        unitId: 4442,
        unitTitle: 'Chủ đề 24 - 有的东西是我的，有的东西是妹妹的。(Có thứ đồ là của tôi, có thứ là của em gái tôi.)',
      },
      {
        unitId: 4443,
        unitTitle: 'Chủ đề 25 - 你们要多听，多说，多读，多写。(Các bạn phải nghe, nói, đọc, viết nhiều.)',
      },
      {
        unitId: 4444,
        unitTitle: 'Bài kiểm tra 5',
      },
      {
        unitId: 4445,
        unitTitle: 'Chủ đề 26 - 地点还没找到。(Vẫn chưa tìm được địa điểm.)',
      },
      {
        unitId: 4446,
        unitTitle: 'Chủ đề 27 - 你常常去图书馆学习吗？(Bạn có thường xuyên đi thư viện học không?)',
      },
      {
        unitId: 4447,
        unitTitle: 'Chủ đề 28 - 她是外语学院最好的学生。(Cô ấy là sinh viên giỏi nhất Học viện Ngoại ngữ.)',
      },
      {
        unitId: 4448,
        unitTitle: 'Chủ đề 29 - 他还高兴地说：谢谢小朋友！ (Ông ấy còn vui vẻ nói: Cảm ơn bạn nhỏ!)',
      },
      {
        unitId: 4449,
        unitTitle: 'Chủ đề 30 - 他在楼上，你想跟他见面吗？ (Anh ấy ở trên tầng, bạn muốn gặp anh ấy không?)',
      },
      {
        unitId: 4450,
        unitTitle: 'Bài kiểm tra 6',
      },
      {
        unitId: 4680,
        unitTitle: 'Đề thi 1',
      },
      {
        unitId: 4681,
        unitTitle: 'Đề thi 2',
      },
      {
        unitId: 4749,
        unitTitle: 'Đề thi 3',
      },
      {
        unitId: 4750,
        unitTitle: 'Đề thi 4',
      },
      {
        unitId: 4751,
        unitTitle: 'Đề thi 5',
      },
      {
        unitId: 4752,
        unitTitle: 'Đề thi 6',
      },
      {
        unitId: 4753,
        unitTitle: 'Đề thi 7',
      },
      {
        unitId: 4754,
        unitTitle: 'Đề thi 8',
      },
      {
        unitId: 4755,
        unitTitle: 'Đề thi 9',
      },
      {
        unitId: 4756,
        unitTitle: 'Đề thi 10',
      },
    ],
    sessions: [
      {
        completionDate: null,
        date: null,
        isScheduled: false,
        overallIndex: 1,
        unitIds: [
          4265,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: null,
        date: null,
        isScheduled: false,
        overallIndex: 2,
        unitIds: [
          4303,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: '2024-12-31',
        date: '2025-01-01',
        isScheduled: true,
        overallIndex: 3,
        unitIds: [
          4305,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: '2024-12-31',
        date: '2025-01-02',
        isScheduled: true,
        overallIndex: 4,
        unitIds: [
          4307,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: null,
        date: null,
        isScheduled: false,
        overallIndex: 5,
        unitIds: [
          4414,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: '2025-01-01',
        date: '2025-01-03',
        isScheduled: true,
        overallIndex: 6,
        unitIds: [
          4707,
        ],
        proficiency: 2,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: '2025-01-02',
        date: '2025-01-04',
        isScheduled: true,
        overallIndex: 7,
        unitIds: [
          4415,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: '2025-01-02',
        date: '2025-01-05',
        isScheduled: true,
        overallIndex: 8,
        unitIds: [
          4418,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: '2025-01-09',
        date: '2025-01-06',
        isScheduled: true,
        overallIndex: 9,
        unitIds: [
          4416,
        ],
        proficiency: 2,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: null,
        date: '2025-01-07',
        isScheduled: true,
        overallIndex: 10,
        unitIds: [
          4417,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-08',
        isScheduled: true,
        overallIndex: 11,
        dayOfWeek: 3,
        unitIds: [
          4419,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-09',
        isScheduled: true,
        overallIndex: 12,
        unitIds: [
          4435,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: null,
        isScheduled: false,
        overallIndex: 13,
        unitIds: [
          4420,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: null,
        date: '2025-01-10',
        isScheduled: true,
        overallIndex: 14,
        unitIds: [
          4421,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-11',
        isScheduled: true,
        overallIndex: 15,
        unitIds: [
          4422,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-12',
        isScheduled: true,
        overallIndex: 16,
        unitIds: [
          4423,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-13',
        isScheduled: true,
        overallIndex: 17,
        unitIds: [
          4424,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-14',
        isScheduled: true,
        overallIndex: 18,
        unitIds: [
          4436,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-15',
        isScheduled: true,
        overallIndex: 19,
        unitIds: [
          4425,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-16',
        isScheduled: true,
        overallIndex: 20,
        unitIds: [
          4426,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-17',
        isScheduled: true,
        overallIndex: 21,
        unitIds: [
          4427,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-18',
        isScheduled: true,
        overallIndex: 22,
        unitIds: [
          4428,
        ],
        proficiency: 1,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-19',
        isScheduled: true,
        overallIndex: 23,
        unitIds: [
          4429,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-20',
        isScheduled: true,
        overallIndex: 24,
        dayOfWeek: 1,
        unitIds: [
          4437,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-21',
        isScheduled: true,
        overallIndex: 25,
        unitIds: [
          4430,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-22',
        isScheduled: true,
        overallIndex: 26,
        unitIds: [
          4431,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-23',
        isScheduled: true,
        overallIndex: 27,
        unitIds: [
          4432,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-24',
        isScheduled: true,
        overallIndex: 28,
        unitIds: [
          4433,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-25',
        isScheduled: true,
        overallIndex: 29,
        unitIds: [
          4434,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-26',
        isScheduled: true,
        overallIndex: 30,
        unitIds: [
          4438,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-27',
        isScheduled: true,
        overallIndex: 31,
        unitIds: [
          4439,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-28',
        isScheduled: true,
        overallIndex: 32,
        unitIds: [
          4440,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-29',
        isScheduled: true,
        overallIndex: 33,
        unitIds: [
          4441,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-30',
        isScheduled: true,
        overallIndex: 34,
        unitIds: [
          4442,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-01-31',
        isScheduled: true,
        overallIndex: 35,
        unitIds: [
          4443,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-01',
        isScheduled: true,
        overallIndex: 36,
        unitIds: [
          4444,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-02',
        isScheduled: true,
        overallIndex: 37,
        unitIds: [
          4445,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: null,
        isScheduled: false,
        overallIndex: 38,
        dayOfWeek: 1,
        unitIds: [
          4446,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: null,
        date: '2025-02-04',
        isScheduled: true,
        overallIndex: 39,
        unitIds: [
          4447,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-05',
        isScheduled: true,
        overallIndex: 40,
        unitIds: [
          4448,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-06',
        isScheduled: true,
        overallIndex: 41,
        unitIds: [
          4449,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-07',
        isScheduled: true,
        overallIndex: 42,
        unitIds: [
          4450,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-08',
        isScheduled: true,
        overallIndex: 43,
        unitIds: [
          4680,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-09',
        isScheduled: true,
        overallIndex: 44,
        unitIds: [
          4681,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-10',
        isScheduled: true,
        overallIndex: 45,
        unitIds: [
          4749,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-11',
        isScheduled: true,
        overallIndex: 46,
        unitIds: [
          4750,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-12',
        isScheduled: true,
        overallIndex: 47,
        unitIds: [
          4751,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-13',
        isScheduled: true,
        overallIndex: 48,
        unitIds: [
          4752,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-14',
        isScheduled: true,
        overallIndex: 49,
        unitIds: [
          4753,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: '2025-02-15',
        isScheduled: true,
        overallIndex: 50,
        unitIds: [
          4754,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
      {
        completionDate: null,
        date: null,
        isScheduled: false,
        overallIndex: 51,
        unitIds: [
          4755,
        ],
        proficiency: 3,
        totalProficiency: 3,
        completed: true,
      },
      {
        completionDate: null,
        date: '2025-02-17',
        isScheduled: true,
        overallIndex: 52,
        unitIds: [
          4756,
        ],
        proficiency: 0,
        totalProficiency: 3,
        completed: false,
      },
    ],
    missions: {
      totalUnits: 52,
      totalCups: 156,
      actualCompletedUnits: 17,
      expectedCompletedUnits: 24,
      earnedCups: 20,
    },
  }
})
